spring:
  application:
    name: gateway_service
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8089/
          predicates:
            - Path=/api/laboratory/**
        - id: r2
          uri: http://localhost:8088/
          predicates:
            - Path=/api/user/**
server:
  port: 8888
